name: Hello World
on:
  pull_request:
    types: [opened]

jobs:
  startup:
    runs-on: ubuntu-latest
    name: Run startup script
    steps:
      - run: echo "Hello World"
  build:
    name: Here is my build task
    runs-on: ubuntu-latest
    needs: startup
    steps:
      - name: Comment on PR
        run: gh pr comment $PR_URL --body "Thanks for your PR. We'll look into it."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
      - name: Check for Buttons
        run: ./.github/scripts/checker.sh
        env:
          FILE: ./src/components/Buttons.js
